services:
  - type: web
    name: sistema-finissimo
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://banco_finiisima_user:McwGm9nHxwU7748XqAy7dM4mQlDxz9a@dpg-d9tim06417fc73egtn30-a.oregon-postgres.render.com:5432/banco_finiisima
      - key: NODE_ENV
        value: production
    plan: free